### ISSUE TITLE
Hard to see time of event

### ISSUE THREAD

**Issue by herrbrixter** [epicarchitect/breakbadhabits#3]
When you add an event, you can set the time. In light mode, the hour and minute digits are hard to see. In dark mode, the AM and PM are hard to see. Please use a different color that has more contrast.

**Comment by epicarchitect** [comment]
@herrbrixter I can't make these colors different, because a third-party library was used for that. And besides, I'm currently rewriting the application completely from scratch. In the new version I will make the time selection different. I hope to release it soon) If you want I can even send you an apk to see what's new there and I am open to suggestions)

**Comment by herrbrixter** [comment]
Alright, I understand. I usually just use the current time. My problem is when I set an earlier time, I can't tell if it is AM or PM in dark mode. Sure, I can try it out.
